var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/families/invites/[code]/route.js")
R.c("server/chunks/[root-of-the-server]__12cbwru._.js")
R.c("server/chunks/03oy_@neondatabase_serverless_index_mjs_0aornz-._.js")
R.c("server/chunks/03oy_bcryptjs_index_02968-~.js")
R.c("server/chunks/familytv_01on8j9._.js")
R.c("server/chunks/[root-of-the-server]__10dv5jl._.js")
R.c("server/chunks/03oy_next_dist_0jwdvcu._.js")
R.c("server/chunks/0b9k__next-internal_server_app_api_families_invites_[code]_route_actions_01y28ou.js")
R.m(229)
module.exports=R.m(229).exports
