// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/albums" | "/albums/[id]" | "/albums/new" | "/app" | "/app/create-family" | "/app/family/[familyId]" | "/app/family/[familyId]/feed" | "/app/family/[familyId]/invite" | "/dashboard" | "/dashboard/notifications" | "/family/[familyId]/settings/invites" | "/invite/[token]" | "/onboarding" | "/onboarding/create-family" | "/onboarding/invite" | "/privacy" | "/profile" | "/settings" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/terms" | "/tv" | "/watch-party/[sessionId]"
type AppRouteHandlerRoutes = "/api/albums" | "/api/albums/[id]" | "/api/comments" | "/api/events" | "/api/events/upcoming" | "/api/families" | "/api/families/[familyId]/invites" | "/api/families/[familyId]/invites/[inviteId]" | "/api/families/invites/[code]" | "/api/families/invites/[code]/accept" | "/api/family" | "/api/family/activity" | "/api/family/presence" | "/api/health" | "/api/invite" | "/api/media" | "/api/notifications" | "/api/posts" | "/api/proxy" | "/api/reactions" | "/api/search" | "/api/socket" | "/api/suggestions" | "/api/sync/clock" | "/api/tv/sessions" | "/api/tv/sync" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/albums": {}
  "/albums/[id]": { "id": string; }
  "/albums/new": {}
  "/api/albums": {}
  "/api/albums/[id]": { "id": string; }
  "/api/comments": {}
  "/api/events": {}
  "/api/events/upcoming": {}
  "/api/families": {}
  "/api/families/[familyId]/invites": { "familyId": string; }
  "/api/families/[familyId]/invites/[inviteId]": { "familyId": string; "inviteId": string; }
  "/api/families/invites/[code]": { "code": string; }
  "/api/families/invites/[code]/accept": { "code": string; }
  "/api/family": {}
  "/api/family/activity": {}
  "/api/family/presence": {}
  "/api/health": {}
  "/api/invite": {}
  "/api/media": {}
  "/api/notifications": {}
  "/api/posts": {}
  "/api/proxy": {}
  "/api/reactions": {}
  "/api/search": {}
  "/api/socket": {}
  "/api/suggestions": {}
  "/api/sync/clock": {}
  "/api/tv/sessions": {}
  "/api/tv/sync": {}
  "/api/upload": {}
  "/app": {}
  "/app/create-family": {}
  "/app/family/[familyId]": { "familyId": string; }
  "/app/family/[familyId]/feed": { "familyId": string; }
  "/app/family/[familyId]/invite": { "familyId": string; }
  "/dashboard": {}
  "/dashboard/notifications": {}
  "/family/[familyId]/settings/invites": { "familyId": string; }
  "/invite/[token]": { "token": string; }
  "/onboarding": {}
  "/onboarding/create-family": {}
  "/onboarding/invite": {}
  "/privacy": {}
  "/profile": {}
  "/settings": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/terms": {}
  "/tv": {}
  "/watch-party/[sessionId]": { "sessionId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
