// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/albums/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/albums/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/albums/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/albums/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/albums/new">> = Specific
  const handler = {} as typeof import("../../src/app/albums/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/albums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/albums">> = Specific
  const handler = {} as typeof import("../../src/app/albums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/create-family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/create-family">> = Specific
  const handler = {} as typeof import("../../src/app/app/create-family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/family/[familyId]/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/family/[familyId]/feed">> = Specific
  const handler = {} as typeof import("../../src/app/app/family/[familyId]/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/family/[familyId]/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/family/[familyId]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/app/family/[familyId]/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/family/[familyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/family/[familyId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/family/[familyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/family/[familyId]/settings/invites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/family/[familyId]/settings/invites">> = Specific
  const handler = {} as typeof import("../../src/app/family/[familyId]/settings/invites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/create-family/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/create-family">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/create-family/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/invite">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tv">> = Specific
  const handler = {} as typeof import("../../src/app/tv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/watch-party/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watch-party/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/watch-party/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/albums/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/albums/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/albums/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/albums/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/albums">> = Specific
  const handler = {} as typeof import("../../src/app/api/albums/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/upcoming/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/upcoming">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/upcoming/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/families/[familyId]/invites/[inviteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[familyId]/invites/[inviteId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/families/[familyId]/invites/[inviteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/families/[familyId]/invites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/[familyId]/invites">> = Specific
  const handler = {} as typeof import("../../src/app/api/families/[familyId]/invites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/families/invites/[code]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/invites/[code]/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/families/invites/[code]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/families/invites/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families/invites/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/api/families/invites/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/families/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/families">> = Specific
  const handler = {} as typeof import("../../src/app/api/families/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family/presence">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/family/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family">> = Specific
  const handler = {} as typeof import("../../src/app/api/family/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/socket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/socket">> = Specific
  const handler = {} as typeof import("../../src/app/api/socket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/clock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/clock">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/clock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tv/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tv/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/tv/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tv/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tv/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/tv/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
