var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/families/invites/[code]/accept/route.js")
R.c("server/chunks/[root-of-the-server]__0n~xs4-._.js")
R.c("server/chunks/03oy_next_dist_0jwdvcu._.js")
R.c("server/chunks/03oy_bcryptjs_index_02968-~.js")
R.c("server/chunks/familytv_01on8j9._.js")
R.c("server/chunks/03oy_0tifiyj._.js")
R.c("server/chunks/[root-of-the-server]__10dv5jl._.js")
R.c("server/chunks/03oy_@neondatabase_serverless_index_mjs_0aornz-._.js")
R.c("server/chunks/09-6_server_app_api_families_invites_[code]_accept_route_actions_01lotzf.js")
R.m(36481)
module.exports=R.m(36481).exports
