module.exports=[93695,(a,b,c)=>{b.exports=a.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},78500,(a,b,c)=>{b.exports=a.x("node:async_hooks",()=>require("node:async_hooks"))},57499,a=>{"use strict";a.i(56071);var b=a.i(56040),c=a.i(48700),d=a.i(18268),e=a.i(96425);let f=new(a.i(78500)).AsyncLocalStorage;var g=a.i(5228);let h=async()=>{var a,h;let i;try{let a=await (0,c.buildRequestLike)(),d=(0,e.getHeader)(a,b.constants.Headers.ClerkRequestData);i=(0,g.decryptClerkRequestData)(d)}catch(a){if(a&&(0,c.isPrerenderingBailout)(a)||a&&(0,c.isClerkUseCacheError)(a))throw a}let j=null!=(h=null==(a=f.getStore())?void 0:a.get("requestData"))?h:i;return(null==j?void 0:j.secretKey)||(null==j?void 0:j.publishableKey)?(0,d.createClerkClientWithOptions)(j):(0,d.createClerkClientWithOptions)({})};var i=a.i(83420);async function j(b){a.r(60401);try{let{userId:a}=await (0,i.auth)({treatPendingAsSignedOut:null==b?void 0:b.treatPendingAsSignedOut});if(!a)return null;return(await h()).users.getUser(a)}catch(a){if((0,c.isClerkUseCacheError)(a))throw a;if((0,c.isNextjsUseCacheError)(a))throw new c.ClerkUseCacheError(`${c.USE_CACHE_ERROR_MESSAGE}

Original error: ${a.message}`,a);throw a}}a.s(["currentUser",0,j],57499)},86513,a=>{a.v("/_next/static/media/favicon.0x3dzn~oxb6tn.ico"+(globalThis.NEXT_CLIENT_ASSET_SUFFIX||""))},48101,a=>{"use strict";let b={src:a.i(86513).default,width:256,height:256};a.s(["default",0,b])},64356,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(989).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/familytv/node_modules/lucide-react/dist/esm/Icon.js <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/familytv/node_modules/lucide-react/dist/esm/Icon.js <module evaluation>","default")},10786,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(989).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/familytv/node_modules/lucide-react/dist/esm/Icon.js from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/familytv/node_modules/lucide-react/dist/esm/Icon.js","default")},29646,a=>{"use strict";a.i(64356);var b=a.i(10786);a.n(b)},59763,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(989).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/familytv/src/app/dashboard/notifications/NotificationsClient.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/familytv/src/app/dashboard/notifications/NotificationsClient.tsx <module evaluation>","default")},91389,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(989).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/familytv/src/app/dashboard/notifications/NotificationsClient.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/familytv/src/app/dashboard/notifications/NotificationsClient.tsx","default")},35475,a=>{"use strict";a.i(59763);var b=a.i(91389);a.n(b)},31725,a=>{"use strict";let b;var c,d,e=a.i(87650),f=a.i(57499);a.i(94755);var g=a.i(2461),h=a.i(97687),i=a.i(15600);let j=null;function k(){if(!j){if(!process.env.DATABASE_URL)throw Error("DATABASE_URL environment variable is not set");j=(0,i.neon)(process.env.DATABASE_URL)}return j}async function l(a,b,c){return k()`
    INSERT INTO users (clerk_id, email, name)
    VALUES (${a}, ${b}, ${c})
    ON CONFLICT (clerk_id) DO UPDATE SET
      email = EXCLUDED.email,
      name = COALESCE(EXCLUDED.name, users.name)
    RETURNING *
  `}async function m(a,b=50){return k()`
    SELECT 
      n.id,
      n.user_id,
      n.type,
      n.related_id,
      n.message,
      n.read,
      n.created_at,
      CASE 
        WHEN n.type = 'post_created' THEN p.content
        WHEN n.type = 'event_reminder' THEN e.title
        ELSE NULL
      END AS related_title
    FROM notifications n
    LEFT JOIN posts p ON n.type = 'post_created' AND n.related_id = p.id
    LEFT JOIN events e ON n.type = 'event_reminder' AND n.related_id = e.id
    WHERE n.user_id = ${a}
    ORDER BY n.created_at DESC
    LIMIT ${b}
  `}var n=a.i(48997);let o=a=>{let b=a.replace(/^([A-Z])|[\s-_]+(\w)/g,(a,b,c)=>c?c.toUpperCase():b.toLowerCase());return b.charAt(0).toUpperCase()+b.slice(1)};var p=a.i(29646);let q=(c="bell",d=[["path",{d:"M10.268 21a2 2 0 0 0 3.464 0",key:"vwvbt9"}],["path",{d:"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326",key:"11g9vi"}]],(b=(0,n.forwardRef)(({className:a,...b},e)=>(0,n.createElement)(p.default,{ref:e,iconNode:d,className:((...a)=>a.filter((a,b,c)=>!!a&&""!==a.trim()&&c.indexOf(a)===b).join(" ").trim())(`lucide-${o(c).replace(/([a-z0-9])([A-Z])/g,"$1-$2").toLowerCase()}`,`lucide-${c}`,a),...b}))).displayName=o(c),b);var r=a.i(35475);async function s(){let a=await (0,f.currentUser)();a||(0,g.redirect)("/sign-in");let[b]=await l(a.id,a.emailAddresses[0]?.emailAddress??"",a.fullName??a.firstName??null),c=await m(b.id),d=c.filter(a=>!a.read).length;return(0,e.jsxs)("div",{className:"min-h-screen bg-background",children:[(0,e.jsx)("header",{className:"border-b bg-card px-4 sm:px-6 py-4",children:(0,e.jsxs)("div",{className:"max-w-2xl mx-auto flex items-center justify-between gap-4",children:[(0,e.jsx)(h.default,{href:"/dashboard",className:"text-sm transition-colors hover:opacity-70 text-muted-foreground",children:"← Back"}),(0,e.jsx)("h1",{className:"font-heading text-lg font-bold text-primary shrink-0",children:"FamilyTV"}),(0,e.jsx)("span",{className:"text-sm text-muted-foreground",children:d>0&&(0,e.jsxs)("span",{className:"inline-flex items-center gap-1 text-primary",children:[(0,e.jsx)(q,{className:"w-4 h-4"}),d]})})]})}),(0,e.jsxs)("main",{className:"max-w-2xl mx-auto px-4 sm:px-6 py-8",children:[(0,e.jsxs)("div",{className:"mb-6",children:[(0,e.jsx)("h2",{className:"font-heading text-2xl font-semibold text-foreground",children:"Notifications"}),(0,e.jsx)("p",{className:"text-sm mt-1 text-muted-foreground",children:"Stay up to date with your family activity"})]}),(0,e.jsx)(r.default,{initialNotifications:c})]})]})}a.s(["default",0,s],31725)},76603,a=>{a.n(a.i(31725))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__0o9hty2._.js.map