var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/families/[familyId]/invites/route.js")
R.c("server/chunks/[root-of-the-server]__0wrgl5-._.js")
R.c("server/chunks/03oy_next_dist_0jwdvcu._.js")
R.c("server/chunks/03oy_bcryptjs_index_02968-~.js")
R.c("server/chunks/familytv_01on8j9._.js")
R.c("server/chunks/03oy_0tifiyj._.js")
R.c("server/chunks/[root-of-the-server]__10dv5jl._.js")
R.c("server/chunks/03oy_@neondatabase_serverless_index_mjs_0aornz-._.js")
R.c("server/chunks/0b9k__next-internal_server_app_api_families_[familyId]_invites_route_actions_0ytcijd.js")
R.m(67691)
module.exports=R.m(67691).exports
