var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/family/activity/route.js")
R.c("server/chunks/[root-of-the-server]__09u985x._.js")
R.c("server/chunks/03oy_@neondatabase_serverless_index_mjs_0aornz-._.js")
R.c("server/chunks/03oy_next_dist_esm_build_templates_app-route_02aa632.js")
R.c("server/chunks/03oy_0tifiyj._.js")
R.c("server/chunks/familytv_01on8j9._.js")
R.c("server/chunks/[root-of-the-server]__10dv5jl._.js")
R.c("server/chunks/03oy_next_dist_0jwdvcu._.js")
R.c("server/chunks/familytv__next-internal_server_app_api_family_activity_route_actions_03.ke6m.js")
R.m(23282)
module.exports=R.m(23282).exports
