var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/upload/route.js")
R.c("server/chunks/[root-of-the-server]__0s6.yyd._.js")
R.c("server/chunks/familytv_01on8j9._.js")
R.c("server/chunks/03oy_next_dist_0jwdvcu._.js")
R.c("server/chunks/[root-of-the-server]__10dv5jl._.js")
R.c("server/chunks/[root-of-the-server]__0~sxnuv._.js")
R.c("server/chunks/03oy_0tifiyj._.js")
R.c("server/chunks/03oy_@neondatabase_serverless_index_mjs_0aornz-._.js")
R.c("server/chunks/familytv__next-internal_server_app_api_upload_route_actions_13i.x-1.js")
R.m(91217)
module.exports=R.m(91217).exports
